version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    image: app
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: .docker/db/Dockerfile
    environment:
      - POSTGRES_USER=eventtool
      - POSTGRES_PASSWORD=eventtool
