spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/eventtool
    username: eventtool
    password: eventtool
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    open-in-view: false
