spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventtool
    username: eventtool
    password: eventtool
  jpa:
    show-sql: true
  flyway:
    user: eventtool
    password: eventtool
